
---
title: "Plotly"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(plotly)
library(tidyr)
library(caret)
library(dplyr)
```

A web application for creating and sharing data visualizations.

###Basic scatterplot
```{r}
data(mtcars)
plot_ly(mtcars, x = mtcars$wt, y = mtcars$mpg, type = "scatter")
#Scatterplot with color on discrete var
plot_ly(mtcars, x = mtcars$wt, y = mtcars$mpg, type = "scatter", color=as.factor(mtcars$cyl))
#Scatterplot with color on cont' var
plot_ly(mtcars, x = mtcars$wt, y = mtcars$mpg, type = "scatter", color=mtcars$disp)
#Scatter plot sizing
plot_ly(mtcars, x = mtcars$wt, y = mtcars$mpg, type = "scatter", color=as.factor(mtcars$cyl), size=mtcars$hp)
# 3D plotting
set.seed(2016-07-21)
temp <- rnorm(100, mean=30, sd=5)
pressure <- rnorm(100)
dtime <- 1:100
plot_ly(x=temp, y=pressure, z=dtime, type="scatter3d", mode="markers", color=temp)
``` 

###Plot_ly line graphs
```{r}
data("airmiles")
plot_ly(x=time(airmiles), y=airmiles, mode="lines")
#Multi line graph
data("EuStockMarkets")
stocks <- as.data.frame(EuStockMarkets) %>%
  gather(index, price) %>%
  mutate(time=rep(time(EuStockMarkets),4))
plot_ly(stocks, x=stocks$time, y=stocks$price, color=stocks$index, mode="lines")
```
  
###Plot_ly and varietiy of plots
```{r}
#Histogram
plot_ly(x=precip, type="histogram")
#Boxplots
plot_ly(iris, y=iris$Petal.Length, color=iris$Species, type="box")
#Heatmap
terrain1 <- matrix(rnorm(100*100), nrow=100, ncol=100)
plot_ly(z=terrain1, type="heatmap")
#3D surface
terrain2 <- matrix(sort(rnorm(100*100)), nrow=100, ncol=100)
plot_ly(z=terrain2, type="surface")
```
  
###Plot_ly with hover effects
```{r}
state_pop <- data.frame(State=state.abb, Pop=as.vector(state.x77[,1]))
state_pop$hover <- with(state_pop, paste(state_pop$State, "<br>", "Population:", state_pop$Pop))
borders <- list(color=toRGB("red"))
map_options <- list(
  scope = "usa",
  projection = list(type="albers usa"),
  showlakes =TRUE,
  lakecolor = toRGB('white')
)
plot_ly(state_pop, z=state_pop$Pop, text=state_pop$hover, locations=state_pop$State, type='choropleth', locationmode='USA-states', color=state_pop$Pop, colors='Blues', marker=list(line=borders)) %>%
  layout(title='US Population in 1975', geo=map_options)
```
  
###Plot_ly and ggplot2
```{r}
set.seed(100)
d <- diamonds[sample(nrow(diamonds), 1000),]

p <- ggplot(data=d, aes(x=carat, y=price))+
  geom_point(aes(text=paste("Clarity:", clarity)), size=4)+
  geom_smooth(aes(colour=cut, fill=cut)) +facet_wrap(~cut)

(gg<-ggplotly(p))
```