---
title: "googleVis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(googleVis)
```

###GoogleVis motion chart
```{r, dependson="gv", results = "asis", cache=TRUE}
M <- gvisMotionChart(Fruits, "Fruit", "Year", options=list(width=600, height=400))
plot(M)
print(M, "chart")
```

###GoogleVis plots on maps
```{r, dependson="gv", results = "asis", cache=TRUE}
G <- gvisGeoChart(Exports, locationvar="Country", colorvar="Profit", options = list(width=600, height=400))
print(G, "chart")
```

###GoogleVis plots on map with specified region
```{r, dependson="gv", results = "asis", cache=TRUE}
G2 <- gvisGeoChart(Exports, locationvar="Country", colorvar="Profit", options = list(width=600, height=400, region="150"))
print(G2, "chart")
```
  
### More options

```{r linechart,dependson="gv",results="asis", cache=TRUE}
df <- data.frame(label=c("US", "GB", "BR"), val1=c(1,3,4), val2=c(23,12,32))
Line <- gvisLineChart(df, xvar="label", yvar=c("val1","val2"),
        options=list(title="Hello World", legend="bottom",
                titleTextStyle="{color:'red', fontSize:18}",                         
                vAxis="{gridlines:{color:'red', count:3}}",
                hAxis="{title:'My Label', titleTextStyle:{color:'blue'}}",
                series="[{color:'green', targetAxisIndex: 0}, 
                         {color: 'blue',targetAxisIndex:1}]",
                vAxes="[{title:'Value 1 (%)', format:'##,######%'}, 
                                  {title:'Value 2 (\U00A3)'}]",                          
                curveType="function", width=500, height=300                         
                ))
print(Line,"chart")
```
  
###Combining plots
```{r linechart,dependson="gv",results="asis", cache=TRUE}
G <- gvisGeoChart(Exports, "Country", "Profit",options=list(width=200, height=100))
T1 <- gvisTable(Exports,options=list(width=200, height=270))
M <- gvisMotionChart(Fruits, "Fruit", "Year", options=list(width=400, height=370))
GT <- gvisMerge(G,T1, horizontal=FALSE)
GTM <- gvisMerge(GT, M, horizontal=TRUE,tableOptions="bgcolor=\"#CCCCCC\" cellspacing=10")
```